apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  diskSelector: ""
  nodeSelector: ""
  recurringJobSelector: '[{"name":"backup", "isGroup":true}]'
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"  # Daily at 2 AM
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 2
  labels:
    job: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "0 */6 * * *"  # Every 6 hours
  task: "snapshot"
  groups:
  - default
  retain: 24
  concurrency: 2
  labels:
    job: snapshot
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: longhorn-snapshot-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: "snap"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    backup-target: s3://longhorn-backups@us-east-1/
    backup-target-credential-secret: longhorn-backup-secret
    allow-node-drain-with-last-healthy-replica: true
    auto-cleanup-system-generated-snapshot: true
    auto-delete-pod-when-volume-detached-unexpectedly: true
    auto-salvage: true
    concurrent-automatic-engine-upgrade-per-node-limit: 3
    create-default-disk-labeled-nodes: true
    default-data-locality: best-effort
    default-data-path: /var/lib/longhorn/
    default-engine-image: longhornio/longhorn-engine:v1.5.3
    default-instance-manager-image: longhornio/longhorn-instance-manager:v1.5.3
    default-share-manager-image: longhornio/longhorn-share-manager:v1.5.3
    delete-removing-failed-node: false
    disable-scheduling-on-cordoned-node: true
    engine-replica-timeout: 8
    fast-replica-rebuild-enabled: false
    guaranteed-engine-manager-cpu: 12
    guaranteed-replica-manager-cpu: 12
    orphan-auto-deletion: true
    priority-class: longhorn-critical
    recurring-successful-jobs-history-limit: 1
    recurring-failed-jobs-history-limit: 1
    replica-soft-anti-affinity: false
    replica-auto-balance: best-effort
    storage-minimal-available-percentage: 25
    storage-over-provisioning-percentage: 100
    support-bundle-failed-history-limit: 1
    system-managed-components-node-selector: ""
    taint-toleration: ""
    upgrade-checker: true
    v1-data-engine: true
    v2-data-engine: false
